run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration

output:
  formats: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  govet:
    enable-all: true
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  funlen:
    lines: 100
    statements: 50
  gosec:
    excludes:
      - G401
      - G501
      - G502
  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

linters:
  disable-all: true
  enable:
    - errcheck     
    - govet        
    - staticcheck  
    - typecheck    
    - gosimple      
    - ineffassign   
    - unused        
    - unconvert     
    - gofmt       
    - goimports    
    - misspell    
    - gosec          
    - goconst      
    - revive       
    - bodyclose    

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - goconst
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path: cmd/
      linters:
        - gochecknoinits
    - path: migrations/
      linters:
        - gomnd
        - goconst
    - linters:
        - lll
      source: "^//go:generate "
  exclude-use-default: false
  exclude:
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
    # govet: Common false positives
    - (possible misuse of unsafe.Pointer|should have signature)
    # staticcheck: Developers tend to write in C-style with an explicit 'break' in a 'switch', so it's ok to ignore
    - ineffective break statement. Did you mean to break out of the outer loop
    # gosec: Too many false-positives on 'unsafe' usage
    - G103
    # gosec: Too many false-positives for parametrized shell calls
    - G204
    # gosec: Duplicated errcheck checks
    - G104
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false 
  uniq-by-line: true