services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=db_username
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=db_name
      - PGDATA=/data/postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -U db_username -d db_name" ]
    ports:
      - "5434:5432"
    volumes:
      - ./postgres_data:/data/postgres
      - ./migrations:/docker-entrypoint-initdb.d/


  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["server"]
    depends_on:
      postgres:
        condition: service_healthy
