package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"moho-router/api/helloworld/v1"
	"moho-router/internal/server/graphql/generated"
)

// SayHello is the resolver for the sayHello field.
func (r *queryResolver) SayHello(ctx context.Context, name string) (*v1.HelloReply, error) {
	req := &v1.HelloRequest{
		Name: name,
	}

	return r.greeterService.SayHello(ctx, req)
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
